apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: {appName}
  name: {appName}
  namespace: {namespace}
spec:
  replicas: 1
  selector:
    deploymentconfig: {appName}
  template:
    metadata:
      labels:
        app: {appName}
        deploymentconfig: {appName}
    spec:
      containers:
      - image: {image}
        imagePullPolicy: Always
        name: {appName}
        ports:
        - containerPort: 8080
          protocol: TCP